/**
 * WHITE NOON — static page generator
 * Assembles every page through the shared layout helpers and writes the .html
 * files Vite consumes as MPA inputs. Deterministic (no timestamps) so rebuilds
 * produce identical output. Run: npm run pages (auto-run by pre{dev,build}).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import content from '../src/data/content.js';
import { renderPage, projectPage, renderCvPage, notFoundMain } from '../src/layout.mjs';
import * as home from '../src/pages/home.mjs';
import * as work from '../src/pages/work.mjs';
import * as method from '../src/pages/method.mjs';
import * as personal from '../src/pages/personal.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

function write(rel, html) {
  const abs = resolve(ROOT, rel);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, html, 'utf8');
  console.log(`  ✓ ${rel}  (${(html.length / 1024).toFixed(1)} KB)`);
}

const standalone = [
  { file: 'index.html', mod: home },
  { file: 'method.html', mod: method },
  { file: 'work/index.html', mod: work },
  { file: 'work/personal.html', mod: personal },
];
for (const { file, mod } of standalone) {
  write(file, renderPage({ ...mod.meta, main: mod.main, content }));
}

for (const slug of ['rag-zelebrix', 'architecture-idea', 'gestamp-agents']) {
  const proj = content.projects[slug];
  write(
    `work/${slug}.html`,
    renderPage({
      title: `${proj.title} — ${content.identity.name}`,
      description: proj.tagline,
      active: 'Work',
      main: projectPage(proj, content),
      content,
    })
  );
}

write('cv.html', renderCvPage(content));

/* ── ASK THE FIELD: build-time knowledge digest (grounding for /api/ask) ──
   The assistant answers ONLY from this digest and cites hrefs from it — the same
   honesty device as the placeholders: nothing invented, every claim has a place
   to verify it. Regenerated on every build from the real content. */
const kProjects = Object.entries(content.projects).map(([slug, pr]) => ({
  title: pr.title, href: `/work/${slug}`, status: pr.statusLabel || pr.status,
  tagline: pr.tagline, role: pr.role, problem: pr.problem,
  stack: pr.stack, outcome: pr.outcome, lessons: pr.lessons,
}));
const KNOWLEDGE = {
  identity: {
    name: content.identity.name, role: 'GenAI engineer', location: 'Madrid, Spain',
    email: content.identity.email, github: content.identity.githubUrl, linkedin: content.identity.linkedinUrl,
    summary: content.hero.sub, availability: content.contact.avail, now: content.about.now,
  },
  pages: [
    { href: '/', title: 'Home', what: 'hero, proof stats, selected work, method teaser, about, contact' },
    { href: '/work', title: 'Work', what: 'all projects: shipped, in progress and planned' },
    { href: '/method', title: 'Method', what: 'how Guillermo works with Claude: principles, workflow phases, toolchain' },
    { href: '/cv', title: 'CV', what: 'print-ready curriculum: experience, education, certifications, skills' },
  ],
  proof: content.proof.map((s) => `${s.num} — ${s.label}`),
  method: {
    href: '/method', thesis: content.method.thesis,
    principles: content.method.principles.map((p) => ({ name: p.name, body: p.body, prevents: p.prevents })),
    phases: content.method.phases.map((f) => ({ name: f.name, exit: f.exit })),
    toolchain: content.method.toolchain.map((t) => `${t.name}: ${t.what}`),
  },
  projects: kProjects,
  experience: [
    'AI Engineer at IDEA (sole AI engineer): designed, built and leads the production RAG platform (Docker, Azure CI/CD, PostgreSQL, Qdrant, RAGAS evals, Langfuse) powering two live assistants.',
    'RAG Chatbot Lead at Zelebrix (payments SaaS): hybrid retrieval (pgvector + Spanish full-text + RRF + cross-encoder rerank + relevance gate), privacy by design (PII scrubbed, tenant data never reaches the external LLM), 150-question golden set.',
    'Data Scientist GenAI at Gestamp (03/2024–present): extended a production multi-agent system on Semantic Kernel (Text-to-SQL with 100% controlled-test accuracy gates, RBAC impersonation, FastAPI streaming, AKS).',
    'MSc Data Science (UAM, 2021–2023) · BSc Computer Engineering (UAM, Erasmus Bergen).',
  ],
};
writeFileSync(resolve(ROOT, 'src/data/knowledge.gen.mjs'),
  `/* GENERATED by scripts/build-pages.mjs — the grounding digest for /api/ask. Do not edit. */\nexport const KNOWLEDGE = ${JSON.stringify(KNOWLEDGE, null, 1)};\n`, 'utf8');
console.log('  ✓ src/data/knowledge.gen.mjs (ask grounding)');
write(
  '404.html',
  renderPage({
    title: `Not found — ${content.identity.name}`,
    description: 'Page not found.',
    active: '',
    main: notFoundMain(),
    content,
  })
);

console.log('\n  9 pages generated.');
